sonar.projectKey=Unitime
sonar.projectName=UniTime
sonar.projectVersion=4.9

sonar.projectBaseDir=C:/Users/kanze/OneDrive/Desktop/unitime2/unitime
sonar.sources=JavaSource
sonar.java.source=11
sonar.java.binaries=.
sonar.working.directory=C:/sonar-tmp

sonar.host.url=http://localhost:9000
sonar.token=sqp_6aa734760da4e82e92efe6143f2e63475156c82b


